[package]
name = "rs"
version = "0.1.0"
authors = ["lythesia <iranaikimi@gmail.com>"]
edition = "2018"

[dependencies]
dissolve = "0.2.2"
reqwest = "0.9.8"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"

[lib]
doctest = false
test = true
